/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_usuario;

import com.squareup.okhttp.FormEncodingBuilder;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;
import com.squareup.okhttp.Response;
import static interfaz_usuario.Interfaz.webClient;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Denis
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */

    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAgregar = new javax.swing.JButton();
        txNombre = new javax.swing.JTextField();
        txPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txNickname = new javax.swing.JTextField();
        txDireccion = new javax.swing.JTextField();
        txTelefono = new javax.swing.JTextField();
        txTarjeta = new javax.swing.JTextField();
        txActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(355, 327));
        setPreferredSize(new java.awt.Dimension(350, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        btAgregar.setText("Registrar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregar);
        btAgregar.setBounds(10, 270, 100, 23);
        getContentPane().add(txNombre);
        txNombre.setBounds(100, 20, 240, 20);
        getContentPane().add(txPassword);
        txPassword.setBounds(100, 50, 240, 20);

        jLabel1.setText("Password:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 90, 14);
        getContentPane().add(txNickname);
        txNickname.setBounds(100, 80, 240, 20);
        getContentPane().add(txDireccion);
        txDireccion.setBounds(100, 110, 240, 20);
        getContentPane().add(txTelefono);
        txTelefono.setBounds(100, 140, 240, 20);
        getContentPane().add(txTarjeta);
        txTarjeta.setBounds(100, 170, 240, 20);
        getContentPane().add(txActual);
        txActual.setBounds(100, 200, 240, 20);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 14);

        jLabel3.setText("Nickname:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 90, 14);

        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 90, 14);

        jLabel5.setText("Tarjeta Credito:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 90, 14);

        jLabel6.setText("Direccion Actual:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 90, 14);

        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 140, 90, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        try {
            String request = addPerson();
            sendRequest(request);

        } catch (IOException ex) {
            Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txActual;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txNickname;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txTarjeta;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables
    public String addPerson() {
        String url="http://localhost:5000/cliente/agregar/"+
                txNombre.getText()+"/"+
                txPassword.getText()+"/"+
                txNickname.getText()+"/"+
                txDireccion.getText()+"/"+
                txTelefono.getText()+"/"+
                txTarjeta.getText()+"/"+
                txActual.getText();
        return url;
    }

    public void sendRequest(String Add) throws IOException {
        URL url = new URL(Add);
        Request request = new Request.Builder().url(url).build();
        Response response = webClient.newCall(request).execute();
        String response_string = response.body().string();
        System.out.println(response_string);
    }
}
